Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.
--

In [1]:
from sklearn.datasets import load_iris

In [10]:
X,y=load_iris(return_X_y=True)

In [13]:
from sklearn.model_selection import train_test_split

In [16]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25,random_state=35)

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
classifier=KNeighborsClassifier()

In [19]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [20]:
y_pred=classifier.predict(X_test)

In [28]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [22]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[14  0  0]
 [ 0 10  2]
 [ 0  1 11]]
0.9210526315789473
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       0.91      0.83      0.87        12
           2       0.85      0.92      0.88        12

    accuracy                           0.92        38
   macro avg       0.92      0.92      0.92        38
weighted avg       0.92      0.92      0.92        38



Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.
--
---

In [15]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [19]:
X_train1, X_test1, y_train1, y_test1=train_test_split(data,target,test_size=0.25,random_state=42)

from sklearn.neighbors import KNeighborsRegressor

regressor=KNeighborsRegressor()
regressor.fit(X_train1,y_train1)
y_pred1=regressor.predict(X_test1)

from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

print(r2_score(y_test1,y_pred1))
print(mean_absolute_error(y_test1,y_pred1))
print(mean_squared_error(y_test1,y_pred1))

0.639665439953224
3.6215748031496067
25.2332


Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.
--
---


In [9]:
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.neighbors import KNeighborsClassifier

iris = load_iris()
X = iris.data
y = iris.target


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


knn_classifier = KNeighborsClassifier()


param_grid = {'n_neighbors': range(1, 21)}


grid_search = GridSearchCV(knn_classifier, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

print("Best K:", grid_search.best_params_['n_neighbors'])
print("Best Accuracy:", grid_search.best_score_)


Best K: 3
Best Accuracy: 0.9583333333333334


Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.
--
---


In [12]:
import pandas as pd
import numpy as np

data_url = "http://lib.stat.cmu.edu/datasets/boston"
raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
target = raw_df.values[1::2, 2]

In [24]:
X2=data
y2=target

from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

X_train2, X_test2, y_train2, y_test2=train_test_split(X2,y2,test_size=0.2,random_state=42)
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train2)
X_test_scaled=scaler.transform(X_test2)

knn_regressor=KNeighborsRegressor()
knn_regressor.fit(X_train_scaled,y_train2)
y_pred2=knn_regressor.predict(X_test_scaled)

print('r2_score: ',r2_score(y_test2,y_pred2))
print('mean_absolute_error: ',mean_absolute_error(y_test2,y_pred2))
print('mean_squared_error: ',mean_squared_error(y_test2,y_pred2))

r2_score:  0.7190172315709293
mean_absolute_error:  2.5921568627450977
mean_squared_error:  20.60552941176471


Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.
--
---


In [38]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.24,random_state=33)
knn=KNeighborsClassifier(weights='distance')

knn.fit(X_train,y_train)
y_pred3=knn.predict(X_test)


print('accuracy_score ',accuracy_score(y_test,y_pred3))
print('classification_report ',classification_report(y_test,y_pred3))

accuracy_score  0.9722222222222222
classification_report                precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.91      1.00      0.95        10
           2       1.00      0.94      0.97        18

    accuracy                           0.97        36
   macro avg       0.97      0.98      0.97        36
weighted avg       0.97      0.97      0.97        36



Q6. Implement a function to standardise the features before applying KNN classifier.
--
---

In [39]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris


def knn_classifier_standardization(X_train,X_test,y_train,y_test,k_neighbors):
    scaler=StandardScaler()
    X_train_scaled=scaler.fit_transform(X_train)
    X_test_scaled=scaler.transform(X_test)
    
    knn_classifier=KNeighborsClassifier(n_neighbors=k_neighbors)
    knn_classifier.fit(X_train_scaled,y_train)
    
    y_pred=knn_classifier.predict(X_test_scaled)
    accuracy= accuracy_score(y_test,y_pred)
    print(f'accuracy {accuracy}')
    


In [43]:
X,y=load_iris(return_X_y=True)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply the KNN classifier with standardization
knn_classifier_standardization(X_train, X_test, y_train, y_test,7)

accuracy 1.0


Q7. Write a Python function to calculate the euclidean distance between two points.
--

In [55]:
import math

def euclidean_distance(point1, point2):
    return math.sqrt(sum((a - b) ** 2 for a, b in zip(point1, point2)))


point1 = (6,2,1)
point2 = (9,4,9)

print(euclidean_distance(point1, point2))


8.774964387392123


Q8. Write a Python function to calculate the manhattan distance between two points.
--


In [54]:
def manhattan_distance(point1, point2):
    return sum(abs(a - b) for a, b in zip(point1, point2))


point1 = (1, 2, 3)
point2 = (4, 5, 6)

print(manhattan_distance(point1, point2)) 


9
